FROM node:24.13.1-slim 

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install --fix-missing -y git curl

ENV SOAJS_DEPLOYER_TYPE=nodejs
ENV NODE_ENV=production
RUN mkdir -p /opt/soajs/soajs.deployer/node_modules
RUN mkdir -p /opt/soajs/tmp
WORKDIR /opt/soajs/soajs.deployer/
COPY ./deployer ./deployer
COPY ./FILES ./FILES
COPY ./package.json ./
RUN npm install
WORKDIR /opt/soajs/soajs.deployer/deployer/

CMD ["/bin/bash"]
