FROM soajsorg/basenginx

ENV NODE_ENV=production
RUN mkdir -p /opt/soajs/soajs.deployer/node_modules
RUN mkdir -p /opt/soajs/tmp
WORKDIR /opt/soajs/soajs.deployer/
COPY . .
RUN npm install
WORKDIR /opt/soajs/soajs.deployer/deployer/

CMD ["/bin/bash"]