FROM ubuntu:16.04
MAINTAINER SOAJS Team <team@soajs.org>

RUN apt-get update && \
    apt-get install --fix-missing -y git curl && \
    curl -sL https://deb.nodesource.com/setup_8.x | bash && \
    apt-get install --fix-missing -y nodejs
RUN apt-get install -y nginx

RUN apt-get install software-properties-common --fix-missing -y && \
	add-apt-repository universe && \
    add-apt-repository ppa:certbot/certbot && \
    apt-get update && \
    apt-get install certbot python-certbot-nginx --fix-missing -y

ENV NODE_ENV=production
RUN mkdir -p /opt/soajs/soajs.deployer/node_modules
RUN mkdir -p /opt/soajs/tmp
WORKDIR /opt/soajs/soajs.deployer/
COPY . .
RUN npm install
WORKDIR /opt/soajs/soajs.deployer/deployer/

CMD ["/bin/bash"]